version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@uniland-ui/utils"
      - dependency-name: "@uniland-ui/styled-system"
    target-branch: "develop"
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: "uniland-ui:core"
